---
title: Accessible Public History
subtitle: CollectionBuilder's Minimalist Approach to Open-Source Collections and Exhibits
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliations:
      - Universität Basel
      - Universität Bern
date: 2023-10-20
categories: Vortrag
event: Universität Bern, DARIAH-CH Study Day
lang: de
doi: 10.5281/zenodo.10003519
citation:
  type: standard
appendix-cite-as: display
other-links:
  - text: 'Veranstaltungswebsite'
    icon: house
    href: 'https://www.dariah.ch/study-day-2023/'
  - text: Slides (Zenodo)
    icon: filetype-pdf
    href: 'https://doi.org/10.5281/zenodo.10003519'
---

## Vortrag

Der Vortrag fand im Rahmen des [Study Days 2023](https://www.dariah.ch/study-day-2023/) von DARIAH-CH an der Universität Bern statt, ist auf Zenodo archiviert und [als PDF-Datei abrufbar](https://doi.org/10.5281/zenodo.10003519).

::: {.callout-tip title="Präsentation anzeigen" icon="false" collapse="true"}

<iframe src="/assets/files/20231020-Moritz_Maehr-DARIAH_CH_Study_Day_2023.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="Accessible Public History">

This browser does not support PDFs. Please download the PDF <a href="/assets/files/20231020-Moritz_Maehr-DARIAH_CH_Study_Day_2023.pdf">download the PDF</a> to view it.

</iframe>
:::

## Abstract

Infrastruktur-Pitch am DARIAH-CH Study Day 2023 von Dr. sc. Moritz Mähr (Digital Lead) zu CollectionBuilder und dessen Anwendungsfall im Projekt Stadt.Geschichte.Basel.

Das Problem mit Public History: Auch wer die eigene digitale Geschichte und die eigenen Daten teilen möchte, hat als Forschende\*r in der Regel weder das Geld für einen kostenpflichtigen Dienst noch die Infrastruktur für eine selbst gehostete Open-Source-Lösung wie Omeka, noch die Zeit oder technischen Kenntnisse, dies selbst zu programmieren. Die Lösung: Mit CollectionBuilder lassen sich digitale Sammlungen, Ausstellungen und Geschichten selbst hosten (mit sehr wenig technischem Know-how), nachhaltig betreiben (Open Source, langzeitarchivierbar) und das kostenlos. Es gibt eine umfangreiche Dokumentation und eine sehr unterstützende Open-Source-Community.

Infrastructure Pitch at the DARIAH-CH Study Day 2023 by Dr. sc. Moritz Mähr (Digital Lead) about CollectionBuilder and its use case in the project Stadt.Geschichte.Basel.

The Problem with Public History: Even if you want to share your digital story and your data, as a researcher you typically don't have the money to use a paid service, the infrastructure for a self-hosted open source solution like Omeka, and the time or technical skills to code it yourself. The Solution: With CollectionBuilder, you can host digital collections, exhibits, and stories, by yourself (with very little technical skill), sustainable (open source, long time archivable), and free of charge. It has an extensive documentation and a very supportive open source community.