---
title: The Urban Fabric as Palimpsest
subtitle: Tracing Proposed Correction Plans in Basel
author:
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
date: 2024-06-25
doi: 10.5281/zenodo.16545009
categories: Vortrag
event: University of Luxembourg, Historical Arguments and the Digital
lang: de
bibliography: references.bib
citation:
  type: standard
  title: 'The Urban Fabric as Palimpsest: Tracing Proposed Correction Plans in Basel'
  container-title: 'Historical Arguments and the Digital, University of Luxembourg'
appendix-cite-as: display
other-links:
  - text: Veranstaltungswebseite
    icon: house
    href: 'https://historicalarguments.wordpress.com/'
  - text: Slides (Zenodo)
    icon: filetype-pdf
    href: 'https://doi.org/10.5281/zenodo.16545009'
---

## Vortrag

Der Vortrag ist Teil des Panels *Politicised Spaces* der Konferenz [Historical Arguments and the Digital](https://historicalarguments.wordpress.com/) am Luxembourg Centre for Contemporary and Digital History.

::: {.callout-tip title="Präsentation anzeigen (Vorschau)" icon="false" collapse="true"}
Diese Ansicht zeigt eine komprimierte Vorschau der Präsentation. Die hochaufgelösten Original-Slides sind [auf Zenodo verfügbar](https://doi.org/10.5281/zenodo.16545009).

<iframe src="/assets/files/240625-Twente-Palimpsest_BS_Preview.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="The Urban Fabric as Palimpsest (Preview)">

This browser does not support PDFs. Please <a href="/assets/files/240625-Twente-Palimpsest_BS_Preview.pdf"">download the PDF</a> to view it.

</iframe>
:::

## Abstract

Wie die meisten Städte der Schweiz wurde auch das heutige Basel massgeblich durch stadtplanerische Entscheidungen der Jahre 1940 bis 1970 geprägt [@eisingerStaedteBauenStaedtebau2004]: Mit dem übergeordneten Ziel der Modernisierung wurden neue Verkehrsinfrastrukturen gebaut, um die Städte besser für den motorisierten Individualverkehr zugänglich zu machen [@avermaeteUrbanDesign20th2021; @burckhardtAchtungSchweizUrtext2019]. Zu diesem Zweck wurden für Basel mehrere sogenannte 'Korrektionspläne' erarbeitet, die den Bau von Autoverkehrsachsen durch die Altstadt vorsahen. Die meisten dieser Pläne wurden nicht vollständig umgesetzt, da eine Stadtplanung, die den privaten Autoverkehr priorisierte, zunehmend auf Kritik stiess [@eisingerZeitgemasseAnachronismenStadtplanerischen2016; @gisler-jauchAutomobil2015]. Dennoch hinterliess das geplante Strassensystem Spuren, und Teilumsetzungen sind bis heute sichtbar. Wir verwenden GIS, um diese Fragmente im Stadtgefüge nachzuzeichnen. Indem wir die Stadtstruktur als Palimpsest lesen [@corbozTerritoriumAlsPalimpsest2001] und so die Überlagerung zeitlicher Schichten offenlegen, die jeweils unterschiedliche gesellschaftspolitische Vorstellungen transportieren [@eisingerStadtArchitektenAnatomie2005], setzen wir uns kritisch mit Erzählungen zur Geschichte Basels auseinander.

Like most cities in Switzerland, present-day Basel was shaped particularly by urban planning decisions made between 1940 and 1970 [@eisingerStaedteBauenStaedtebau2004]: With the underlying goal of modernization, new transport infrastructures were built to make cities more accessible to cars [@avermaeteUrbanDesign20th2021; @burckhardtAchtungSchweizUrtext2019]. To this end, several so-called 'Korrektionspläne' were drawn up for Basel that proposed the construction of automobile traffic axes through the Old Town. Most of these plans were not fully executed, since urban planning that prioritized private cars was met with increasing criticism [@eisingerZeitgemasseAnachronismenStadtplanerischen2016; @gisler-jauchAutomobil2015]. Nevertheless, the planned road system left a mark and partial implementations can still be seen today. We use GIS to trace these fragments in the urban fabric. By reading the city structure as a palimpsest [@corbozTerritoriumAlsPalimpsest2001] to expose the superimposition of temporal layers that each convey different sociopolitical ideas [@eisingerStadtArchitektenAnatomie2005], we critically engage with narratives about the history of Basel.

Ausgangspunkt ist die Innenstadt mit ihren jahrhundertealten Gebäuden und engen Gassen, die den weitreichenden Einfluss der Korrektionspläne auf die Altstadt verschleiern. Die bestehende Forschung konzentriert sich darauf, dass der Strassenbau vor allem im Bereich des Rümelinsplatzes stattfand und danach aufgegeben wurde [vgl. @russiBaslerPlaetzeVisitenkarten2022; @huberArchitekturfuehrerBaselBaugeschichte2014; @fingerhuthBautenFuerBasel1988]. Um dieser Erzählung entgegenzuwirken, zerlegen wir die im Lauf der Zeit entstandenen Schichten der gebauten Umwelt, um aufzuzeigen, wie heterogen die Innenstadt tatsächlich ist.

Our starting point is the city center with its centuries-old buildings and narrow alleys which mask the extensive influence the correction plans had on the 'Altstadt'. Existing research focuses on how road construction mainly took place in the area around Rümelinsplatz and was abandoned after that [cf. @russiBaslerPlaetzeVisitenkarten2022; @huberArchitekturfuehrerBaselBaugeschichte2014; @fingerhuthBautenFuerBasel1988]. To counter this narrative, we dissect the layers formed by the built environment over time to illustrate how heterogenous the city center really is.

Zweitens erweitern wir den Fokus unserer Analyse: Während sich die bestehende Forschung zu den Korrektionsplänen vor allem auf die Innenstadt und insbesondere die Rolle der 'Talentlastungsstrasse' zwischen Rümelinsplatz und Fischmarkt/Blumenrain konzentriert [@russiBaslerPlaetzeVisitenkarten2022; @huberArchitekturfuehrerBaselBaugeschichte2014; @zauggStadtentwicklungBaselsSeit2010; @brunnerBaulicheEntwicklungStadt1999], versuchen wir, die konkreten Auswirkungen der Pläne auf gesamtstädtischer Ebene nachzuzeichnen. Neben der Darstellung des Ausmasses, in dem der autogerechte Planungsansatz baulich umgesetzt wurde, erlaubt uns dies, seine Auswirkungen zwischen verschiedenen Stadtteilen zu vergleichen, etwa: Betreffen die verschiedenen Pläne besonders Arbeiterquartiere? Zeigt sich im Vergleich zur Innenstadt ein höherer Anteil umgesetzter Vorschläge in Quartieren, die erst später gebaut wurden?

Secondly, we extend the scope of our analysis: Whereas existing research on the correction plans mostly zooms in on the center and specifically the role of the 'Talentlastungsstrasse' between Rümelinsplatz and Fischmarkt/Blumenrain [@russiBaslerPlaetzeVisitenkarten2022; @huberArchitekturfuehrerBaselBaugeschichte2014; @zauggStadtentwicklungBaselsSeit2010; @brunnerBaulicheEntwicklungStadt1999], we seek to retrace the plans' specific impact on a city-wide level. In addition to demonstrating the scope of the design the automotive planning approach was translated into, this allows us to compare its impact between different parts of the city, e.g.: Do the various plans especially affect working class districts? Compared to the city center, can we see a higher share of implemented proposals in neighborhoods that were constructed more recently?

Statt einer Geschichte einzelner Gebäude nähern wir uns der gebauten Umwelt mit dem Instrumentarium der Stadtmorphologie [@mohleStadtplananalyseHistorischmethodischeEinfuhrung2018]: Wir georeferenzieren die Planungsdokumente, die den in den Korrektionsplänen vorgeschlagenen Änderungen entsprechen, und kartieren sie mittels GIS gegen räumliche Kategorien wie die oben genannten, um morphologischen Wandel oder Beständigkeit in der Bebauungsstruktur zu prüfen [@malfroyMorphologischeBetrachtungsweiseStadt2018]. Da morphologische Analysen als interpretative Akte verstanden werden [@corbozGeschichteStadtebausAls2001], untersuchen wir, wie lange längst überholte urbanistische Konzepte im heutigen Baugefüge noch weithin nachwirken, obschon die substanziellsten Teile der Korrektionspläne in den 1970er-Jahren zurückgezogen wurden [@mohleProfanesImHerzen2016].

Instead of a history of individual buildings, we approach the built environment with the toolkit of urban morphology [@mohleStadtplananalyseHistorischmethodischeEinfuhrung2018]: We georeference the planning documents that correspond to changes proposed in the correction plans and use GIS to map them against spatial categories, such as the ones mentioned above, checking for morphological change or permanence in building structures [@malfroyMorphologischeBetrachtungsweiseStadt2018]. With morphological analyses seen as interpretative acts [@corbozGeschichteStadtebausAls2001], we investigate how long outdated concepts of urbanism still resonate widely in the contemporary building fabric even though the most substantial parts of the correction plans were withdrawn in the 1970s [@mohleProfanesImHerzen2016].