---
title: Digital Longevity
subtitle: Learnings from the (Digital) History Project Stadt.Geschichte.Basel
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel, Universität Bern
date: 2023-12-12
categories: Vortrag
event: Max-Planck-Institut für Rechtsgeschichte und Rechtstheorie, Legal History Meets Digital Humanities
lang: de
bibliography: references.bib
nocite: |
  @*
doi: 10.5281/zenodo.10368874
citation:
  type: standard
appendix-cite-as: display
other-links:
  - text: 'Veranstaltungswebsite'
    icon: house
    href: 'https://www.lhlt.mpg.de/events/36152/3251077/'
  - text: Slides (Zenodo)
    icon: filetype-pdf
    href: 'https://doi.org/10.5281/zenodo.10368874'
  - text: 'Videoaufzeichnung (YouTube)'
    icon: camera-reels
    href: 'https://www.youtube.com/watch?v=6JO7y0MIpsA'
---

## Vortrag

Der Vortrag fand im Rahmen des Seminars [Legal History Meets Digital Humanities](https://www.lhlt.mpg.de/events/36152/3251077/) des Max-Planck-Instituts für Rechtsgeschichte und Rechtstheorie statt, ist auf Zenodo archiviert und [als PDF-Datei abrufbar](https://doi.org/10.5281/zenodo.10368874).

::: {.callout-tip title="Präsentation anzeigen" icon="false" collapse="true"}
<iframe src="/assets/files/20231212-Moritz_Maehr-Digital_Longevity.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="Digital Longevity: Learnings from the (Digital) History Project Stadt.Geschichte.Basel">

This browser does not support PDFs. Please download the PDF <a href="/assets/files/20231212-Moritz_Maehr-Digital_Longevity.pdf">download the PDF</a> to view it.

</iframe>
:::

Ein Videomitschnitt ist [auf YouTube verfügbar](https://www.youtube.com/watch?v=6JO7y0MIpsA).

::: {.callout-tip title="Videomitschnitt anzeigen" icon="false" collapse="true"}
<iframe width="610" height="334" loading="lazy" src="https://www.youtube.com/embed/6JO7y0MIpsA" title="[Ep. 5] Digital Longevity: Learnings from the (Digital) History Project Stadt.Geschichte.Basel" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>

</iframe>
:::

## Abstract

::: {lang="de"}
Diese Session behandelt die zentrale Herausforderung der digitalen Langlebigkeit im Bereich der Digital History, mit Fokus auf das Public-History-Projekt Stadt.Geschichte.Basel. Im Zentrum steht das Endings Project der University of Victoria, das ein umfassendes Prinzipienset zur Sicherstellung der Nachhaltigkeit digitaler Projekte vorschlägt. Diese Prinzipien betonen die Bedeutung offener Datenformate, detaillierter Dokumentation, sorgfältiger redaktioneller Bearbeitung, eines nutzerzentrierten Produktdesigns ohne serverseitige Abhängigkeiten sowie eines strategischen Release-Management-Protokolls, um die mit einem möglichen „digitalen dunklen Zeitalter“ verbundenen Risiken zu mindern. Das Projekt Stadt.Geschichte.Basel veranschaulicht die Anwendung dieser Prinzipien und zeigt, wie eine öffentlich finanzierte Digital-History-Initiative langfristige Erhaltung und Offenheit erreichen kann. Das Projekt betont die Notwendigkeit eines fortlaufenden Stakeholder-Engagements, interdisziplinärer Zusammenarbeit sowie der Anwendung von nutzerzentriertem Design für eine inklusive und wirksame Nutzerbeteiligung. Es unterstreicht die Bedeutung iterativer Verfeinerung im Entwicklungsprozess, um die technischen und organisatorischen Komplexitäten zu bewältigen, die mehreren Anspruchsgruppen inhärent sind. Indem Best Practices aus der Erfahrung von Stadt.Geschichte.Basel abgeleitet werden, trägt diese Session zum Diskurs über Projektmanagement in der Digital History bei und dient als Leitfaden für die Schaffung resilienter, nutzerzentrierter und nachhaltig verwalteter digitaler Ressourcen.
:::

::: {lang="en"}
This session explores the critical challenge of digital longevity in the field of digital history, with a focus on the public history project Stadt.Geschichte.Basel. It highlights the Endings Project at the University of Victoria, which proposes a comprehensive framework of principles to ensure the sustainability of digital projects. These principles emphasize the importance of open data formats, detailed documentation, rigorous editing, user-centric product design without server-side dependencies, and a strategic release management protocol to mitigate the risks associated with a potential "digital dark age". The Stadt.Geschichte.Basel project exemplifies the application of these principles and demonstrates how a publicly funded digital history initiative can achieve long-term preservation and openness. The project emphasizes the need for ongoing stakeholder engagement, interdisciplinary collaboration, and the application of user-centered design for inclusive and effective user participation. It emphasizes the importance of iterative refinement in the development process to address the technical and organizational complexities inherent in multi-stakeholder settings. By extracting best practices from the Stadt.Geschichte.Basel experience, this session contributes to the discourse on project management in digital history and serves as a guide for creating resilient, user-centered, and sustainably managed digital resources.
:::