---
title: Navigating Disconcertment in Map-Making
subtitle: How to Turn Conflict and Collaboration into Accessible Geodata
author:
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliations:
        - Universität Basel
        - Universität Bern
date: 2025-07-18
doi: 10.5281/zenodo.16042822
categories: Vortrag
event: Universidade NOVA de Lisboa, DH2025
lang: de
bibliography: references.bib
citation:
  type: standard
  title: 'Navigating Disconcertment in Map-Making: How to Turn Conflict and Collaboration into Accessible Geodata'
  container-title: 'Digital Humanities 2025, Universidade NOVA de Lisboa'
appendix-cite-as: display
other-links:
  - text: Veranstaltungswebseite
    icon: house
    href: 'https://dh2025.adho.org/'
  - text: Panelprogramm (Conftool)
    icon: calendar4-range
    href: 'https://www.conftool.pro/dh2025/index.php?page=browseSessions&form_session=187'
  - text: Slides (Zenodo)
    icon: filetype-pdf
    href: 'https://doi.org/10.5281/zenodo.16042822'
  - text: 'Videoaufzeichnung (Zenodo)'
    icon: camera-reels
    href: 'https://doi.org/10.5281/zenodo.18484300'
---

## Vortrag

Der Vortrag ist Teil der Session [Long Paper-23](https://www.conftool.pro/dh2025/index.php?page=browseSessions&form_session=187) der Konferenz [Digital Humanities 2025](https://dh2025.adho.org/) an der Universidade NOVA de Lisboa. Eine Videoaufzeichnung des Vortrags ist [auf Zenodo verfügbar](https://doi.org/10.5281/zenodo.18484300).

::: {.callout-tip title="Präsentation anzeigen (Vorschau)" icon="false" collapse="true"}
Diese Ansicht zeigt eine komprimierte Vorschau der Präsentation. Die hochaufgelösten Original-Slides sind [auf Zenodo verfügbar](https://doi.org/10.5281/zenodo.16042822).

<iframe src="/assets/files/20250718-Twente_Maehr_Disconcertment-Preview.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="Navigating Disconcertment in Map-Making (Preview)">

This browser does not support PDFs. Please <a href="/assets/files/20250718-Twente_Maehr_Disconcertment-Preview.pdf">download the PDF</a> to view it.

</iframe>
:::

## Abstract

Karten sind nicht nur eine wichtige Quellengattung für die Geschichtswissenschaft, sondern auch epistemische Werkzeuge [@bertinSemiologyGraphicsDiagrams2010; @kramerFigurationAnschauungErkenntnis2016; @goodwinReadingGraphsMaps2011]. Sie fungieren als Boundary Objects, indem sie einen Rahmen für die Strukturierung von Forschung, die Formulierung von Hypothesen und die Zusammenarbeit über Disziplingrenzen hinweg bieten [@wildisen-muenchKartenAlsBoundary2023]. Nach der Erstellung von Dutzenden Karten für die zehnbändige Buchreihe [Stadt.Geschichte.Basel](https://stadtgeschichtebasel.ch) betrachten wir Karten nicht nur als Vermittler von Zusammenarbeit, sondern widmen uns der Frage, wie der Prozess des Gestaltens, Publizierens und Nachnutzens von Kartendaten spezifisch durch Eigenschaften von Geodaten beeinflusst wird. Wir argumentieren, dass diese Eigenschaften prägen, wie Data Stewards mit Konflikten rund um divergierende Anforderungen an Kartengestaltungen umgehen, und zeigen, wie sich dies auf die Publikation offener Forschungsdaten auswirkt.

Maps are not only an important source genre for historical studies, but also epistemic tools [@bertinSemiologyGraphicsDiagrams2010; @kramerFigurationAnschauungErkenntnis2016; @goodwinReadingGraphsMaps2011]. They function as boundary objects in providing a framework for structuring research, establishing hypotheses and facilitating collaboration across disciplines [@wildisen-muenchKartenAlsBoundary2023]. After the creation of dozens of maps for the ten-volume book series [Stadt.Geschichte.Basel](https://stadtgeschichtebasel.ch), we consider maps not only as facilitators of collaboration but are drawn to the question of how the process of designing, publishing and reusing map data is influenced by characteristics of geodata specifically. We argue that these features shape the way data stewards handle conflicts related to diverging requirements for map designs and show how this factors into the publication of open research data.

Im interdisziplinären Forschungsprojekt Stadt.Geschichte.Basel unterstützt das [Team für Forschungsdatenmanagement (FDM)](/team.qmd) über 70 Archäolog\*innen und Historiker\*innen bei der Erforschung der Geschichte Basels von frühen Siedlungsspuren (50'000 Jahre vor unserer Zeit) bis in die Gegenwart. Das Team betreut die vielfältigen im Projekt genutzten Datentypen, nicht zuletzt in allen Belangen der Visualisierung räumlicher Zusammenhänge mittels Karten. Karten gehören zu den häufigsten Datentypen in unserem Projekt [@mahrDigitalLongevityLearnings2023]: Sie liefern visuelle Evidenz, die sich qualitativ grundlegend von Texten, Listen und Tabellen unterscheidet, und können sehr komplexe Zusammenhänge auf kleinem Raum vermitteln. Zudem dienen sie im Forschungsprozess als Ordnungssysteme, die helfen, Hypothesen zu bilden und zu prüfen [@bodenhamerChasingBakhtinsGhost2018; @coleDigitalMapping2021; @duringHermeneuticsDataNetworks2015]. Das FDM-Team unterstützt Forschende aller beteiligten Disziplinen bei der Erstellung wissenschaftlicher Abbildungen mit massgeschneiderten Lösungen und macht dabei das Fachwissen sichtbar, das nötig ist, um Karten zu erstellen, die druckreif sind, als digitale Publikation funktionieren und obendrein FAIR verfügbar sind.

At the interdisciplinary research project Stadt.Geschichte.Basel, the [Research Data Management (RDM) Team](/team.qmd) supports over 70 archaeologists and historians in investigating the history of Basel from traces of early settlements (50'000 before our time) to the present day. The team handles a variety of data types that are used in the project, not least in all matters relating to the visualization of spatial relationships using maps. Maps are one of the most common data types in our project [@mahrDigitalLongevityLearnings2023]: They provide visual evidence that is qualitatively fundamentally different from texts, lists and tables, and can convey very complex relationships in a small space. They also serve as organisational systems in the research process, helping to form and test hypotheses [@bodenhamerChasingBakhtinsGhost2018; @coleDigitalMapping2021; @duringHermeneuticsDataNetworks2015]. The RDM team assists researchers from all involved disciplines with the creation of scientific illustrations with tailor-made solutions, highlighting the specialist knowledge needed for the making of maps that are ready for printing, work as a digital publication and, on top, are FAIRly available.

Wir verwenden 'Karte', um die Ergebnisse der Aufgabe unseres Teams zu beschreiben, historische Argumente zu visualisieren. Dieser Prozess beginnt oft damit, das zu vermittelnde Argument als Aussage über Beziehungen zwischen Datenpunkten zu behandeln. Für die Visualisierung konzentrieren wir uns auf die Räumlichkeit eines Arguments (verstanden als konzeptuelle Verbindungen zwischen Entitäten). Um eine menschlich wahrnehmbare Version der hinter dem Argument stehenden Datenpunkte und ihrer Verbindungen zu schaffen, kodieren wir die konzeptuelle Räumlichkeit des Arguments mit Geodatensätzen, die in Form einer Karte dargestellt werden können [@fairbairnEpistemologicalThoughtsSuccess2021].

We use 'map' to describe the results of our team's task of visualizing historical arguments. This process often starts by treating the argument to be made as a statement about relations of data points. We focus on an argument's spatiality (meaning conceptual connections between entities) for visualization purposes. To create a human-perceivable version of data points behind the argument and their connections, we encode the argument's conceptual spatiality with geospatial datasets that can be displayed in the form of a map [@fairbairnEpistemologicalThoughtsSuccess2021].

Bei der Untersuchung der Rolle, die unsere Datensätze sowohl bei der Gestaltung des Forschungsoutputs als auch bei der Strukturierung der Interaktionen zwischen Autor\*innen, Designer\*innen, Herausgebenden und Nutzenden spielen, decken wir Dynamiken in drei Phasen auf – Recherche, Aufbereitung und FAIR-Publikation. Wir vertreten die These, dass die Reibung, auf die wir im Datenlebenszyklus des Projekts zwischen den Akteur\*innen beim Entwerfen, Verhandeln und Kompromissesuchen stossen, nicht nur unserer Arbeitsweise inhärent, sondern auch dem Ergebnis zuträglich ist – und dies insbesondere aufgrund der räumlichen Natur unserer Daten. Mithilfe des Konzepts der Disconcertment [@verranScienceAfricanLogic2001] zeigen wir, wie wir Konflikte zwischen epistemischen Gemeinschaften nicht durch das Auflösen von Reibung, sondern durch das Annehmen der Gleichzeitigkeit scheinbar widersprüchlicher Sichtweisen und Konventionen im Umgang mit räumlichen Daten in produktive Momente verwandeln. Mit Fokus auf diesen Teil des Workflows zeigen wir, wie die räumlichen Eigenschaften unserer Daten mit dem iterativen Gestaltungsprozess und mit Konflikten zwischen Designer\*innen, Forschenden, Herausgebenden und Datennutzenden zusammenhängen. Unser Output – sowohl druckfähige wissenschaftliche Abbildungen und (Geo-)Datenpublikationen als auch die Architektur unserer [Forschungsdatenplattform](/products/coding/plattform/index.qmd) – ist somit das Ergebnis gezielt kultivierter Momente der Disconcertment.

Investigating the role our datasets play in both shaping the research output and structuring the interactions between authors, designers, publishers, and consumers, we uncover dynamics in three phases – researching, processing and FAIR publication. We hold that in the project's data life cycle, the friction we encounter between the actors in drafting, negotiating and compromising is not only inherent to the way we work, but beneficial to the output – and specifically related to the spatial nature of our data. Using the concept of disconcertment [@verranScienceAfricanLogic2001], we show how we turn conflicts between epistemic communities into productive moments not by resolving friction, but by embracing the simultaneity of seemingly contradictory views and conventions on working with spatial data. Focusing our analysis on this part of the workflow, we show how the spatial features of our data relate to the iterative design process and to conflicts between designers, researchers, publishers, and data consumers. Our output, both printable scientific illustrations and (geo)data publications, as well as the architecture of our [open research data platform](/products/coding/plattform/index.qmd), then is the result of purposefully cultivated sensations of disconcertment.

Die breite Verwendung von Karten über Disziplingrenzen hinweg macht sie zu einer geeigneten Fallstudie für die Rolle von Datenaufbereitung und -publikation in unserem Workflow. Indem wir sie in unserem Projekt als Boundary Objects charakterisieren, haben wir erkannt, dass die von uns erstellten Karten und die zugrundeliegenden Geodaten leicht an unterschiedliche Anforderungen anpassbar sind und dabei zugleich über einzelne Anwendungen hinweg gemeinsame Merkmale beibehalten [@starInstitutionalEcologyTranslations1989a]. Im Prozess der Kartenerstellung für Stadt.Geschichte.Basel arbeitet das FDM-Team mit vielen Anspruchsgruppen zusammen, um präzise und ästhetisch ausgewogene Karten zu schaffen, die mit aktueller Technologie entwickelt und mit diskriminierungsfreien Metadaten angereichert werden [@maehrHandbuchZurErstellung2024a]. Nach der Druckpublikation werden sowohl Karten als auch die zugehörigen Geodaten für die Online-Publikation aufbereitet und auf der Stadt.Geschichte.Basel-[Forschungsdatenplattform](https://forschung.stadtgeschichtebasel.ch) zugänglich gemacht [@mahrStadtGeschichteBaselResearchData2024]. Dieser Prozess der Umwandlung von Rohdaten in gedruckte Karten, digitale Karten und nachnutzbare Geodaten, die online in einem eigens entwickelten Repositorium verfügbar gemacht werden, unterstreicht, dass es sich nicht um statische Produkte, sondern um das Ergebnis kollektiver Praktiken handelt [@raaschHelenVerranPionierin2014]. Wir identifizieren zwei Perspektiven, um unseren Workflow und das Zusammenspiel zwischen Akteur\*innen und Daten weiter zu untersuchen: eine projektinterne Perspektive mit Fokus auf Autor\*innen, Setzer\*innen und Designer\*innen einerseits sowie eine output-orientierte Perspektive andererseits, die auf Implikationen für die Nachnutzung unserer Daten durch Nutzende unserer Forschungsdatenplattform abzielt.

The widespread use of maps across disciplines makes them a suitable case study for the role of processing and publication of data within our workflow. Characterizing them as boundary objects in our project, we recognized that the maps and underlying geospatial data we produce are easily adaptable to meet varying requirements and at the same time maintain common characteristics across individual applications [@starInstitutionalEcologyTranslations1989a]. Within the process of creating maps for Stadt.Geschichte.Basel, the RDM Team engages with many stakeholders to create accurate and aesthetically balanced maps developed with up-to-date technology, enriched with non-discriminatory metadata [@maehrHandbuchZurErstellung2024a]. After print publication, both maps and corresponding geodata are being prepared for online publication and made accessible on the Stadt.Geschichte.Basel [Open Research Data Platform](https://forschung.stadtgeschichtebasel.ch) [@mahrStadtGeschichteBaselResearchData2024]. This process of transforming raw data into printed maps, digital maps, and reusable geodata, made available online in a specifically developed repository, stresses that we are not dealing with static products but a result of collective practices [@raaschHelenVerranPionierin2014]. We identify two perspectives to further investigate our workflow and the interplays between actors and data: a project-internal angle focusing on authors, typesetters, and designers on the one hand, and an output-oriented angle, aiming for implications for the reuse of our data by users of our research data platform.

Wir gehen der Frage nach, wie diese Rolle von Karten die interdisziplinäre Kommunikation erleichtert, gleichzeitig aber auch Herausforderungen für die Wahrung der Datenintegrität und der Treue zu den ursprünglichen Intentionen der Autor\*innen mit sich bringt. Redaktionelle Entscheidungen zu Symbolik, Dateistrukturen, Formaten und Genauigkeitsgraden können zu Ergebnissen führen, die von dem abweichen, was die Autor\*innen ursprünglich geliefert haben. Bei der Arbeit mit Daten der Archäologischen Bodenforschung Basel-Stadt etwa entstehen Diskrepanzen aufgrund unterschiedlicher disziplinärer Standards und Erwartungen. Die Notwendigkeit, komplexe historische Raumdaten für die Publikation in einer koordinierten Buchreihe anzupassen, führt zu interpretativen Schichten, die die ursprünglichen Befunde verdecken oder verändern können, etwa durch Auslassungen oder Kürzungen aufgrund der durch das verfügbare Druckformat gesetzten Grenzen. In manchen Fällen führte dies zu Konfliktsituationen, in denen die Designer\*innen durch Auswählen, Weglassen und Gestalten einen Weg nach vorn finden mussten. Anhand konkreter Beispiele aus dem Forschungsprojekt veranschaulichen wir, wie in dieser internen Perspektive epistemische Konflikte rund um stilistische, redaktionelle, technische und ästhetische Entscheidungen entstanden. Statt für ein blosses Auflösen der Reibung zu plädieren, zeigen wir, wie wir Momente epistemischer Verwirrung bewältigten, indem wir uns auf unsere Disconcertment einliessen und einen Weg aus der Aporie fanden, indem wir uns zu Unterbestimmtheit bekannten, ohne zu verschweigen oder zu homogenisieren [@yasunoriBecomingKnowerApory2024; @raaschIntroducingStudentsSTS2018].

We delve into how this role of maps facilitates interdisciplinary communication while also introducing challenges in maintaining data integrity and fidelity to the authors' original intentions. Editorial decisions regarding symbology, file structures, formats, and levels of accuracy can lead to outcomes that deviate from what authors initially provided. For example, when working with data from the Archäologische Bodenforschung Basel-Stadt (Cantonal Agency for Archaeological soil research), discrepancies arise due to differing disciplinary standards and expectations. The necessity to adapt complex historical spatial data for publication in a coordinated book series introduces interpretative layers that may obscure or alter the original findings, e.g. by omission or abridgements due to constraints set by available paper formats for printing. In some cases, this led to conflicting situations where the designers had to determine a way forward by choosing, omitting and styling. Using concrete examples from the research project, we illustrate how in this internal angle, epistemic conflicts arose relating to stylistic, editorial, technical and aesthetic decisions. Arguing for not simply resolving friction, we show how we handled moments of epistemic confusion by engaging with our disconcertment and finding our way out of apory through committing to under-determination without silencing and homogenizing [@yasunoriBecomingKnowerApory2024; @raaschIntroducingStudentsSTS2018].

Mit Blick auf die Perspektive der Datennutzenden (Forschende, Studierende) beleuchten wir sodann die Mechanismen der Publikation von Roh- und aufbereiteten Daten auf der offenen Forschungsdatenplattform des Projekts: Die Bereitstellung von Forschungsdaten zur Erkundung und zum Download mittels interaktiver Webtechnologien zeigt auf, dass unser Projektoutput nur eine von vielen Möglichkeiten ist, die Daten zu visualisieren und zu interpretieren. Indem wir bewusst die Kontrolle über Visualisierung, Interpretation und Weiternutzung abgeben, eröffnen wir Raum für alternative Lesarten historischer Argumente, fördern die Neuimagination historischer Narrative und erkennen an, dass die Nutzenden unserer offenen Forschungsdaten nicht nur Datenkonsument\*innen, sondern selbst auch Datenproduzent\*innen sind [@maehrGeschichteBaselIns2024].

Then, turning to the perspective of data consumers (researchers, students), we highlight the mechanisms of publishing raw and processed data on the project's open research data platform: Making research data available for exploration and download using interactive web technologies sheds light on how our project output is only one of a multitude of ways to visualize and interpret the data. By deliberately ceding control over visualization, interpretation and further usage, we open up for alternative readings of historical arguments, fostering re-imaginations of historical narratives and acknowledge that the users of our open research data are not only data consumers but also data producers themselves [@maehrGeschichteBaselIns2024].

Auch in dieser output-orientierten Perspektive analysieren wir, wie unser Workflow den Umgang mit Konflikten ermöglicht, die aus der räumlichen Natur unserer Daten entstehen: Unsere Plattform unterstützt umfangreiche Datensätze mit hoher Granularität, während gedruckte Karten aufgrund von Platzbeschränkungen und dem Bedürfnis nach Klarheit eine Vereinfachung erfordern. Diese Diskrepanz kann bei Mitwirkenden erneute Disconcertment auslösen, wenn sie das Gefühl haben, dass wesentliche Aspekte ihrer Daten nach der ersten Aufbereitung zu einer druckfähigen Karte verloren gehen oder falsch dargestellt werden. Zudem gehen wir der Frage nach, dass nicht nur der Wechsel von Papier zu Internet ein entscheidender Faktor ist, sondern auch die notwendige Metadaten-Annotation des gesamten Datensatzes bezüglich Karteninhalt sowie GIS-bezogene Annotationen der als GeoJSON publizierten Rohgeodaten. Um die Zugänglichkeit unserer Forschungsdaten zu erhöhen, haben wir mit [Leaflet](https://leafletjs.com/), einer Open-Source-JavaScript-Bibliothek für Karten, einen interaktiven Viewer entwickelt. Aufgrund von Einschränkungen bei der Zugänglichmachung historischer interaktiver Karten werden unsere Datensätze jedoch auf zeitgenössische Karten unterschiedlicher Eignung projiziert, was zu anachronistischen Interpretationen führen oder Nuancen der historischen Geografie übersehen lassen kann. Die Herausforderung liegt darin, Zugänglichkeit mit der Verantwortung in Einklang zu bringen, komplexe zeitliche und räumliche Zusammenhänge akkurat zu vermitteln. Ebenso führt die Darstellung historischer räumlicher Merkmale mittels gängiger Repräsentationen wie Polygonen und Punktmarkierungen eine Spezifität in den Datensatz ein, die übermässig determinierend sein und historische Ambiguität sowie Schichten wissenschaftlicher Interpretation überdecken kann.

Also in this outbound perspective, we analyze how our workflow accommodates handling conflicts resulting from the spatial nature of our data: Our platform supports extensive datasets with high granularity, while printed maps require simplification due to spatial constraints and the need for clarity. This disparity can create renewed disconcertment among collaborators who may feel that essential aspects of their data are lost or misrepresented after initial processing into a printable map. Additionally, we delve into how not only the change from paper to internet is a crucial factor, but also the necessary metadata annotation for the whole data set regarding the map content and GIS-related annotations regarding the raw geodata which is published as geojson. To increase accessibility of our research data, we developed an interactive viewer using [Leaflet](https://leafletjs.com/), an open-source JavaScript library for maps. However, due to constraints pertaining to the accessibility of historical interactive maps, our data sets are superimposed onto contemporary maps of varying suitability, potentially leading to anachronistic interpretations or overlooking nuances of historical geography. The challenge lies in balancing accessibility with the responsibility of accurately conveying complex temporal and spatial relationships. Similarly, displaying historical spatial features using common representations such as polygons and point markers introduces a specificity into the data set which may be overly deterministic, covering historical ambiguity and layers of scholarly interpretation.

Erneut greifen wir auf Verrans Arbeit zurück, um diese Unzulänglichkeiten verunsichernder, anachronistischer und interaktiver Visualisierungen als nützliche Instrumente der Wissensproduktion zu begreifen. Anhand konkreter Beispiele zeigen wir, wie dieser Ansatz zur Publikation räumlicher Daten mögliche Nachnutzungsszenarien verbessert und dabei der wissenschaftlichen Genauigkeit verpflichtet bleibt. Wir veranschaulichen, wie die Struktur der von Stadt.Geschichte.Basel entwickelten Forschungsdatenplattform die Nachnutzung der zugänglichen Forschungsdaten fördert und Raum für generative Disconcertment lässt, während sie zugleich an Projektmanagement-Richtlinien festhält, die Prinzipien nutzerzentrierten Designs folgen, transdisziplinäre Integration fördern und asymmetrischen Machtverhältnissen entgegenwirken [@maehrGeschichteBaselIns2024].

Again, we turn to Verran's work for seeing these shortcomings of disconcerting anachronistic and interactive visualizations as useful devices in knowledge production. With concrete examples, we demonstrate how this approach to publishing spatial data enhances possible reuse scenarios while staying committed to scientific accuracy. We illustrate how the structure of the research data platform developed by Stadt.Geschichte.Basel promotes reuse of the accessible research data and leaves room for generative disconcertment while otherwise still adhering to project management guidelines that follows principles for user-centered design, advocating transdisciplinary integration and working against asymmetrical power relations [@maehrGeschichteBaselIns2024].

In der Analyse des Einflusses unserer Daten auf sowohl die interne als auch die output-orientierte Perspektive der Kartenerstellung plädieren wir für die bewusste Nutzung von Disconcertment. Wir tun dies, indem wir Beispiele aus dem Projekt Stadt.Geschichte.Basel zeigen, die veranschaulichen, wie wir mit den räumlichen Daten inhärenten Ambiguitäten und Komplexitäten bei der Kartenerstellung und auf unserer offenen Forschungsdatenplattform umgehen, indem wir Disconcertment kultivieren. Dies fördert ein partizipatives Modell der Digital History, das zu einer kritischen Auseinandersetzung mit historischer Geografie einlädt. Wir erörtern, wie wir durch die Pflege verunsichernder Empfindungen zugängliche Karten schaffen, die sowohl visuell überzeugend als auch epistemisch transparent sind. Mit unserem Projekt eröffnen wir Räume für die Neuimagination historischer Narrative und die Unterstützung reflexiver, inklusiver Wissenschaft.

In the analysis of our data's influence on both in- and outbound perspectives of map making, we advocate for making use of disconcertment. We do so by showing examples from the Stadt.Geschichte.Basel project, illustrating how we deal with ambiguities and complexities inherent in spatial data during map creation and on our open research data platform by cultivating disconcertment. This fosters a participatory model of digital history that invites critical engagement with historical geography. We discuss how, by tending to disconcerting sensations, we produce accessible maps that are both visually compelling and epistemically transparent. With our project, we open up spaces for re-imagining historical narratives and supporting reflexive, inclusive scholarship.