---
title: Forschungsdatenplattform
subtitle: forschung.stadtgeschichtebasel.ch
author:
  - name: Moritz Mähr
    email: moritz.maehr@gmail.com
    orcid: 0000-0002-1367-1618
    affiliation: Universität Basel
  - name: Nico Görlich
    orcid: 0000-0003-3860-1488
    affiliation: Universität Basel
  - name: Moritz Twente
    email: mtwente@protonmail.com
    orcid: 0009-0005-7187-9774
    affiliation: Universität Basel
date-modified: last-modified
lang: de
other-links:
  - text: Website
    icon: house
    href: 'https://forschung.stadtgeschichtebasel.ch/'
code-links:
  - href: 'https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/'
    text: GitHub Repository
    icon: github
---

## Plattform

Lorem Ipsum

## Datenmodell

Metadaten für die auf der Forschungsdatenplattform vorgestellten Elemente werden gemäss einem Datenmodell bereitgestellt, das vom Team für Forschungdatenmanagement der Stadt.Geschichte.Basel entwickelt wurde, um den Anforderungen der vielfältigen im Projekt verwendeten Quellen gerecht zu werden. Das Datenmodell (und der anschliessende Annotationsprozess) folgen dem Handbuch zur Erstellung diskriminerungsfreier Metadaten für historische Quellen und Forschungsdaten, das ebenfalls von Stadt.Geschichte.Basel entwickelt wurde.

Die folgende Grafik veranschaulicht das Datenmodell mit Metadatenfeldern für ein Beispiel-Metadatenobjekt `sgb01313`, das ein untergeordnetes Medienobjekt `m01313` hat. Wenn ein Metadatenobjekt mehr als ein untergeordnetes Medienobjekt hat, werden die id-Nummern der untergeordneten Objekte fortlaufend nummeriert: `m01313_1`, `m01313_2` usw.

```{mermaid}
classDiagram
direction LR
    class metadata {
        id (sgb01313)
        title
        [subject;subject]
        description
        temporal
        [isPartOf;isPartOf] (Data DOIs)
    }
    class media {
        id (m01313)
        title
        [subject;subject] (keywords from GenderOpen Index)
        description
        [creator] (incl. link to Wikidata)
        [publisher] (incl. link to Wikidata)
        date
        temporal
        type
        format
        extent
        [source] (Source and catalogue link)
        language (ISO 639-2 code)
        [relation] (internal links to other items, link to GitHub, further information)
        rights
        license
    }
    metadata "n" --> "m" media
```
